// Code generated by MockGen. DO NOT EDIT.
// Source: domain/repository/review_repository.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	gomock "github.com/golang/mock/gomock"
	entity "github.com/tockn/diff-mvc-and-ca/domain/entity"
	reflect "reflect"
)

// MockReview is a mock of Review interface
type MockReview struct {
	ctrl     *gomock.Controller
	recorder *MockReviewMockRecorder
}

// MockReviewMockRecorder is the mock recorder for MockReview
type MockReviewMockRecorder struct {
	mock *MockReview
}

// NewMockReview creates a new mock instance
func NewMockReview(ctrl *gomock.Controller) *MockReview {
	mock := &MockReview{ctrl: ctrl}
	mock.recorder = &MockReviewMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockReview) EXPECT() *MockReviewMockRecorder {
	return m.recorder
}

// FindByID mocks base method
func (m *MockReview) FindByID(id int64) (*entity.Review, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*entity.Review)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID
func (mr *MockReviewMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockReview)(nil).FindByID), id)
}

// Save mocks base method
func (m *MockReview) Save(rate float64) (*entity.Review, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", rate)
	ret0, _ := ret[0].(*entity.Review)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save
func (mr *MockReviewMockRecorder) Save(rate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockReview)(nil).Save), rate)
}

// SumOfRateByItemID mocks base method
func (m *MockReview) SumOfRateByItemID(id int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SumOfRateByItemID", id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SumOfRateByItemID indicates an expected call of SumOfRateByItemID
func (mr *MockReviewMockRecorder) SumOfRateByItemID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SumOfRateByItemID", reflect.TypeOf((*MockReview)(nil).SumOfRateByItemID), id)
}

// CountByItemID mocks base method
func (m *MockReview) CountByItemID(id int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByItemID", id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByItemID indicates an expected call of CountByItemID
func (mr *MockReviewMockRecorder) CountByItemID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByItemID", reflect.TypeOf((*MockReview)(nil).CountByItemID), id)
}
