// Code generated by MockGen. DO NOT EDIT.
// Source: usecase/review_usecase.go

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	gomock "github.com/golang/mock/gomock"
	input "github.com/tockn/diff-mvc-and-ca/usecase/input"
	output "github.com/tockn/diff-mvc-and-ca/usecase/output"
	reflect "reflect"
)

// MockReview is a mock of Review interface
type MockReview struct {
	ctrl     *gomock.Controller
	recorder *MockReviewMockRecorder
}

// MockReviewMockRecorder is the mock recorder for MockReview
type MockReviewMockRecorder struct {
	mock *MockReview
}

// NewMockReview creates a new mock instance
func NewMockReview(ctrl *gomock.Controller) *MockReview {
	mock := &MockReview{ctrl: ctrl}
	mock.recorder = &MockReviewMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockReview) EXPECT() *MockReviewMockRecorder {
	return m.recorder
}

// Get mocks base method
func (m *MockReview) Get(ipt *input.GetReview) (*output.Review, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ipt)
	ret0, _ := ret[0].(*output.Review)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockReviewMockRecorder) Get(ipt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockReview)(nil).Get), ipt)
}

// Post mocks base method
func (m *MockReview) Post(ipt *input.PostReview) (*output.Review, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Post", ipt)
	ret0, _ := ret[0].(*output.Review)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Post indicates an expected call of Post
func (mr *MockReviewMockRecorder) Post(ipt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Post", reflect.TypeOf((*MockReview)(nil).Post), ipt)
}
